### User sing up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Prem Acharya",
    "company": "Company name",
    "address": "Some address Sydney",
    "phone": "400000001",
    "email": "jha94567@gmail.com",
    "password": "secret222"
}
### User sing in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json 

{
    "email": "e2@e.com",
     "password": "password"   
}

### Get a user profile endpoint
GET  http://localhost:3001/v1/user
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUyQGUuY29tIiwiaWF0IjoxNjI0NDYyNjMwLCJleHAiOjE2MjQ1NDkwMzB9.nPQyHjIq-cJsxjlzUQYiU93G4II2v8WUOQNZCOu36Bc


###Token routers

### Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUyQGUuY29tIiwiaWF0IjoxNjI0NDM2MDEzLCJleHAiOjE2MjcwMjgwMTN9.BnX-9Ko80nfTC7kcTW_pCw64Q4rkcsv92K8h--4tc4Q


# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUyQGUuY29tIiwiaWF0IjoxNjA0OTc0MTcyLCJleHAiOjE2MDQ5NzUwNzJ9.wvNH_c-yaWd05N6sPx3Y47AtJIIP9dXNCOIyVEjUO88


#### Password reset request endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json 

{
    "email": "e2@e.com"
}
#### Update new password endpoint
PATCH  http://localhost:3001/v1/user/reset-password
Content-Type: application/json 

{
    "email": "e2@e.com",
    "pin": "995241",
    "newPassword": "password"
}

#### user logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUyQGUuY29tIiwiaWF0IjoxNjI0NDM2Mjc5LCJleHAiOjE2MjQ1MjI2Nzl9.qNyRnQHkBi2IxGTxKnfDbO1Xy30b0JLJqVTlpR23-PE
 
 
###Ticket apis

 
### Open new ticket
POST http://localhost:3001/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUyQGUuY29tIiwiaWF0IjoxNjA5ODkxOTg0LCJleHAiOjE2MDk5NzgzODR9.7cUfpK_RF68a-xfxVXuet4PWVqwToUPyDXpupFlCQNI
Content-Type: application/json 

{
 "subject": "Form Issue",
  "sender": "Prem",
  "message": "1 Contact form not working. please fix it as soon as possible" 
}

###Get all the tickets
GET http://localhost:3001/v1/ticket
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUyQGUuY29tIiwiaWF0IjoxNjA5ODkyOTMxLCJleHAiOjE2MDk5NzkzMzF9.sPqRPk6nKGpS5tMK0uYIJv778CWBfyn3zm_Y9iTS4Iw

### Get single ticket
GET http://localhost:3001/v1/ticket/5fcd969896b6cb084ceafd19
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUyQGUuY29tIiwiaWF0IjoxNjA5ODkxOTg0LCJleHAiOjE2MDk5NzgzODR9.7cUfpK_RF68a-xfxVXuet4PWVqwToUPyDXpupFlCQNI

### Reply message to the ticket
PUT http://localhost:3001/v1/ticket/5fcd969896b6cb084ceafd19
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUyQGUuY29tIiwiaWF0IjoxNjA5ODkxOTg0LCJleHAiOjE2MDk5NzgzODR9.7cUfpK_RF68a-xfxVXuet4PWVqwToUPyDXpupFlCQNI
Content-Type: application/json 

{ 
    "message": "this is the 222 reply", 
    "sender": "Prem" 
}

### Close the ticket
PATCH http://localhost:3001/v1/ticket/close-ticket/5fcd969896b6cb084ceafd19
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUyQGUuY29tIiwiaWF0IjoxNjA5OTA0NjQyLCJleHAiOjE2MDk5OTEwNDJ9.hRSVE-AFfMnsnxgCouqV_W2U5A2nfVLOBClPE59GGls

### Delete the ticket
DELETE  http://localhost:3001/v1/ticket/5fcd969896b6cb084ceafd19
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUyQGUuY29tIiwiaWF0IjoxNjA5ODkxOTg0LCJleHAiOjE2MDk5NzgzODR9.7cUfpK_RF68a-xfxVXuet4PWVqwToUPyDXpupFlCQNI

